### ISSUE TITLE
Disk space error with v3 to v4 migration script

### ISSUE THREAD

**Issue by joelcieslar** [EasyEngine/easyengine#1312]
I am trying to migrate from v3 to v4 using the provided script (migrate.sh) - https://easyengine.io/handbook/v3-to-v4-migration/script/

However, I am faced with the following error after executing `sudo bash ./migrate.sh --all`:

```
web@xenon:~$ sudo bash migrate.sh --all
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8214  100  8214    0     0   229k      0 --:--:-- --:--:-- --:--:--  229k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10589  100 10589    0     0   344k      0 --:--:-- --:--:-- --:--:--  344k
 !     We require at least 5 GiB disk space free
Disk space is too low to continue migration
```

Here is the output of `df`:

```
web@xenon:~$ df
Filesystem     1K-blocks    Used Available Use% Mounted on
udev              981128       0    981128   0% /dev
tmpfs             199208     676    198532   1% /run
/dev/sda1       19626788 3115528  15667240  17% /
tmpfs             996040       0    996040   0% /dev/shm
tmpfs               5120       0      5120   0% /run/lock
tmpfs             996040       0    996040   0% /sys/fs/cgroup
tmpfs             199208       0    199208   0% /run/user/1000
```

I am using Ubuntu 18.04.1 LTS.

**Comment by mbtamuli** [comment]
Thanks for reporting this. There was an issue with the script and it has been fixed.

**Comment by mbtamuli** [comment]
@joelcieslar I am sorry, it was pushed to a wrong branch, I've updated it and the same link should work now.
```
wget -O migrate.sh https://rt.cx/ee3to4 && chmod +x migrate.sh
```

**Comment by joelcieslar** [comment]
Thanks, I appreciate your help with this. This issue seems to have been fixed, but unfortunately I've encountered another.

After running `sudo ./migrate.sh --all`:

```
=====> Downlading EasyEngine v4
-----> Downloading EasyEngine phar
--2018-11-24 22:09:54--  https://raw.githubusercontent.com/EasyEngine/easyengine-builds/master/phar/easyengine.phar
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.244.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.244.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5370362 (5.1M) [application/octet-stream]
Saving to: ‘/usr/local/bin/ee4’

/usr/local/bin/ee4                  100%[================================================================>]   5.12M  --.-KB/s    in 0.1s    

2018-11-24 22:09:54 (46.6 MB/s) - ‘/usr/local/bin/ee4’ saved [5370362/5370362]

PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in phar:///usr/local/bin/ee4/vendor/easyengine/admin-tools-command/src/Admin_Tools_Command.php on line 183
PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in phar:///usr/local/bin/ee4/vendor/easyengine/admin-tools-command/src/Admin_Tools_Command.php on line 183
PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in phar:///usr/local/bin/ee4/vendor/easyengine/admin-tools-command/src/Admin_Tools_Command.php on line 183
PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in phar:///usr/local/bin/ee/vendor/easyengine/admin-tools-command/src/Admin_Tools_Command.php on line 183
-----> Switching EasyEngine v4 sites to port 80
-----> Disabling EasyEngine v3.
PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in phar:///usr/local/bin/ee/vendor/easyengine/admin-tools-command/src/Admin_Tools_Command.php on line 183
PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in phar:///usr/local/bin/ee4/vendor/easyengine/admin-tools-command/src/Admin_Tools_Command.php on line 183
PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in phar:///usr/local/bin/ee4/vendor/easyengine/admin-tools-command/src/Admin_Tools_Command.php on line 183
sed: can't read docker-compose.yml: No such file or directory
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
Error: No such container: ee-global-redis
PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in phar:///usr/local/bin/ee/vendor/easyengine/admin-tools-command/src/Admin_Tools_Command.php on line 183
-----> Replacing `ee` executable with EasyEngine v4.
-----> Now running `ee` will execute EasyEngine v4.
-----> Migration is complete.
```

Despite saying "migration is complete", my website seems to be down. Not to worry though, I have restored a backup. :relaxed:

**Comment by mbtamuli** [comment]
@mrrobot47 Please take a look at this. This looks like an issue in [the code](https://github.com/EasyEngine/admin-tools-command/blob/develop/src/Admin_Tools_Command.php#L183).

Ref: https://stackoverflow.com/questions/592322/php-expects-t-paamayim-nekudotayim

**Comment by ovidiubica** [comment]
I confirm, migrations are still broken. I only tried the remote approach though.

**Comment by luisgennari** [comment]
I have 5.3GB of free disk space but i still get error when i try to migrate:
! We require at least 5 GiB disk space free Disk space is too low to continue migration

My `df` output:

```
luis@eletron:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.8G     0  1.8G   0% /dev
tmpfs           370M  876K  369M   1% /run
/dev/sda1       9.6G  4.3G  5.3G  45% /
tmpfs           1.9G     0  1.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/loop0       55M   55M     0 100% /snap/google-cloud-sdk/62
/dev/loop1       90M   90M     0 100% /snap/core/6034
/dev/loop2       55M   55M     0 100% /snap/google-cloud-sdk/63
/dev/loop3       90M   90M     0 100% /snap/core/6130
/dev/loop4       55M   55M     0 100% /snap/google-cloud-sdk/64
/dev/loop5       89M   89M     0 100% /snap/core/5897
/dev/sda15      105M  3.4M  102M   4% /boot/efi
tmpfs           370M     0  370M   0% /run/user/1001
```

**Comment by daghendrik** [comment]
I am getting errors during migrating as well:

```
root@MYSERVER:/# wget -O migrate.sh https://rt.cx/ee3to4 &&
> chmod +x migrate.sh
--2019-07-03 14:43:13--  https://rt.cx/ee3to4
Resolving rt.cx (rt.cx)... 104.18.36.157, 104.18.37.157, 2606:4700:30::6812:259d                                                                                                                                                                                                                                             , ...
Connecting to rt.cx (rt.cx)|104.18.36.157|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/easyengine/installer/master/migratio                                                                                                                                                                                                                                             n/migrate.sh [following]
--2019-07-03 14:43:13--  https://raw.githubusercontent.com/easyengine/installer/                                                                                                                                                                                                                                             master/migration/migrate.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133                                                                                                                                                                                                                                             , 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.13                                                                                                                                                                                                                                             3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8721 (8.5K) [text/plain]
Saving to: ‘migrate.sh’

100%[======================================>] 8,721       --.-K/s   in 0s

2019-07-03 14:43:13 (79.8 MB/s) - ‘migrate.sh’ saved [8721/8721]

root@MYSERVER:/# sudo ./migrate.sh mydomain.com

-----> The following sites will be migrated:
=====> mydomain.com
 !     The staging acknowledgement is pending.
-----> You need to create ~/staging_acknowledgement.txt
-----> and then put the following in the file to start the migration.
migrate=YES
Script will continue after staging acknowledgement.
root@MYSERVER:/# sudo touch ~/staging_acknowledgement.txt
root@MYSERVER:/# sudo nano ~/staging_acknowledgement.txt
root@MYSERVER:/# sudo ./migrate.sh mydomain.com

-----> The following sites will be migrated:
=====> mydomain.com
-----> Checking dependencies
-----> Installing Docker
-----> Installing Docker-Compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   2502      0 --:--:-- --:--:-- --:--:--  2508
100 15.4M  100 15.4M    0     0  96789      0  0:02:47  0:02:47 --:--:--  117k
-----> Installing PHP
-----> Installing PHP extensions
-----> Installed PHP : 5
-----> Checking if required PHP modules are installed...
-----> pcntl is already installed
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libwireshark3 libwiretap3 libwsutil3 linux-headers-3.13.0-129
  linux-headers-3.13.0-129-generic linux-headers-3.13.0-132
  linux-headers-3.13.0-132-generic linux-headers-3.13.0-133
  linux-headers-3.13.0-133-generic linux-headers-3.13.0-135
  linux-headers-3.13.0-135-generic linux-headers-3.13.0-137
  linux-headers-3.13.0-137-generic linux-headers-3.13.0-139
  linux-headers-3.13.0-139-generic linux-headers-3.13.0-141
  linux-headers-3.13.0-141-generic linux-headers-3.13.0-142
  linux-headers-3.13.0-142-generic linux-headers-3.13.0-143
  linux-headers-3.13.0-143-generic linux-headers-3.13.0-144
  linux-headers-3.13.0-144-generic linux-headers-3.13.0-147
  linux-headers-3.13.0-147-generic linux-headers-3.13.0-43
  linux-headers-3.13.0-43-generic linux-headers-3.13.0-52
  linux-headers-3.13.0-52-generic linux-image-3.13.0-129-generic
  linux-image-3.13.0-132-generic linux-image-3.13.0-133-generic
  linux-image-3.13.0-135-generic linux-image-3.13.0-137-generic
  linux-image-3.13.0-139-generic linux-image-3.13.0-141-generic
  linux-image-3.13.0-142-generic linux-image-3.13.0-143-generic
  linux-image-3.13.0-144-generic linux-image-3.13.0-147-generic
  linux-image-3.13.0-43-generic linux-image-3.13.0-52-generic
  linux-image-extra-3.13.0-129-generic linux-image-extra-3.13.0-132-generic
  linux-image-extra-3.13.0-133-generic linux-image-extra-3.13.0-135-generic
  linux-image-extra-3.13.0-137-generic linux-image-extra-3.13.0-139-generic
  linux-image-extra-3.13.0-141-generic linux-image-extra-3.13.0-142-generic
  linux-image-extra-3.13.0-143-generic linux-image-extra-3.13.0-144-generic
  linux-image-extra-3.13.0-147-generic linux-image-extra-3.13.0-43-generic
  linux-image-extra-3.13.0-52-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
-----> curl is already installed
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libwireshark3 libwiretap3 libwsutil3 linux-headers-3.13.0-129
  linux-headers-3.13.0-129-generic linux-headers-3.13.0-132
  linux-headers-3.13.0-132-generic linux-headers-3.13.0-133
  linux-headers-3.13.0-133-generic linux-headers-3.13.0-135
  linux-headers-3.13.0-135-generic linux-headers-3.13.0-137
  linux-headers-3.13.0-137-generic linux-headers-3.13.0-139
  linux-headers-3.13.0-139-generic linux-headers-3.13.0-141
  linux-headers-3.13.0-141-generic linux-headers-3.13.0-142
  linux-headers-3.13.0-142-generic linux-headers-3.13.0-143
  linux-headers-3.13.0-143-generic linux-headers-3.13.0-144
  linux-headers-3.13.0-144-generic linux-headers-3.13.0-147
  linux-headers-3.13.0-147-generic linux-headers-3.13.0-43
  linux-headers-3.13.0-43-generic linux-headers-3.13.0-52
  linux-headers-3.13.0-52-generic linux-image-3.13.0-129-generic
  linux-image-3.13.0-132-generic linux-image-3.13.0-133-generic
  linux-image-3.13.0-135-generic linux-image-3.13.0-137-generic
  linux-image-3.13.0-139-generic linux-image-3.13.0-141-generic
  linux-image-3.13.0-142-generic linux-image-3.13.0-143-generic
  linux-image-3.13.0-144-generic linux-image-3.13.0-147-generic
  linux-image-3.13.0-43-generic linux-image-3.13.0-52-generic
  linux-image-extra-3.13.0-129-generic linux-image-extra-3.13.0-132-generic
  linux-image-extra-3.13.0-133-generic linux-image-extra-3.13.0-135-generic
  linux-image-extra-3.13.0-137-generic linux-image-extra-3.13.0-139-generic
  linux-image-extra-3.13.0-141-generic linux-image-extra-3.13.0-142-generic
  linux-image-extra-3.13.0-143-generic linux-image-extra-3.13.0-144-generic
  linux-image-extra-3.13.0-147-generic linux-image-extra-3.13.0-43-generic
  linux-image-extra-3.13.0-52-generic
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
-----> sqlite3 not installed. Installing...
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php5-sqlite3
-----> zip is already installed
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php5-sqlite3
-----> Checking swap
=====> Downlading EasyEngine v4
-----> Downloading EasyEngine phar
--2019-07-03 14:53:36--  https://raw.githubusercontent.com/EasyEngine/easyengine-builds/master/phar/easyengine.phar
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5571254 (5.3M) [application/octet-stream]
Saving to: ‘/usr/local/bin/ee4’

100%[===================================================================================================================================================================================================================================================================================>] 5,571,254   --.-K/s   in 0.05s

2019-07-03 14:53:36 (100 MB/s) - ‘/usr/local/bin/ee4’ saved [5571254/5571254]

PHP Parse error:  syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in phar:///usr/local/bin/ee4/vendor/easyengine/auth-command/src/Auth_Command.php on line 657
PHP Parse error:  syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in phar:///usr/local/bin/ee4/vendor/easyengine/auth-command/src/Auth_Command.php on line 657
PHP Parse error:  syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in phar:///usr/local/bin/ee4/vendor/easyengine/auth-command/src/Auth_Command.php on line 657
Error: no such column: php_version

Migrating site: mydomain.com

EE3 site type:
./migrate.sh: line 153: ee3_ee4_site_type_map: bad array subscript
EE4 site type:
Creating  in EasyEngine v4. This may take some time please wait...
./migrate.sh: line 157: ee3_ee4_site_type_map: bad array subscript
PHP Parse error:  syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in phar:///usr/local/bin/ee4/vendor/easyengine/auth-command/src/Auth_Command.php on line 657
Copying site contents
sending incremental file list
file has vanished: "/proc/10/exe"
rsync: symlink "/proc/.self.4290" -> "4289" failed: No such file or directory (2)
rsync: symlink "/proc/.thread-self.4290" -> "4289/task/4289" failed: No such file or directory (2)
file has vanished: "/proc/10/task/10/exe"
file has vanished: "/proc/11/exe"
file has vanished: "/proc/11/task/11/exe"
file has vanished: "/proc/12/exe"
file has vanished: "/proc/12/task/12/exe"
file has vanished: "/proc/125/exe"
file has vanished: "/proc/125/task/125/exe"
file has vanished: "/proc/128/exe"
file has vanished: "/proc/128/task/128/exe"
file has vanished: "/proc/13/exe"
file has vanished: "/proc/13/task/13/exe"
file has vanished: "/proc/130/exe"
file has vanished: "/proc/130/task/130/exe"
file has vanished: "/proc/133/exe"
file has vanished: "/proc/133/task/133/exe"
file has vanished: "/proc/134/exe"
file has vanished: "/proc/134/task/134/exe"
file has vanished: "/proc/135/exe"
file has vanished: "/proc/135/task/135/exe"
file has vanished: "/proc/139/exe"
file has vanished: "/proc/139/task/139/exe"
file has vanished: "/proc/14/exe"
file has vanished: "/proc/14/task/14/exe"
file has vanished: "/proc/140/exe"
file has vanished: "/proc/140/task/140/exe"
file has vanished: "/proc/142/exe"
file has vanished: "/proc/142/task/142/exe"
file has vanished: "/proc/143/exe"
file has vanished: "/proc/143/task/143/exe"
file has vanished: "/proc/1438/exe"
file has vanished: "/proc/1438/task/1438/exe"
file has vanished: "/proc/144/exe"
file has vanished: "/proc/144/task/144/exe"
file has vanished: "/proc/15/exe"
file has vanished: "/proc/15/task/15/exe"
file has vanished: "/proc/16/exe"
file has vanished: "/proc/16/task/16/exe"
file has vanished: "/proc/17/exe"
file has vanished: "/proc/17/task/17/exe"
file has vanished: "/proc/18/exe"
file has vanished: "/proc/18/task/18/exe"
file has vanished: "/proc/19/exe"
file has vanished: "/proc/19/task/19/exe"
file has vanished: "/proc/2/exe"
file has vanished: "/proc/2/task/2/exe"
file has vanished: "/proc/20/exe"
file has vanished: "/proc/20/task/20/exe"
file has vanished: "/proc/21/exe"
file has vanished: "/proc/21/task/21/exe"
file has vanished: "/proc/22/exe"
file has vanished: "/proc/22/task/22/exe"
file has vanished: "/proc/23/exe"
file has vanished: "/proc/23/task/23/exe"
file has vanished: "/proc/24/exe"
file has vanished: "/proc/24/task/24/exe"
file has vanished: "/proc/25/exe"
file has vanished: "/proc/25/task/25/exe"
file has vanished: "/proc/26/exe"
file has vanished: "/proc/26/task/26/exe"
file has vanished: "/proc/28/exe"
file has vanished: "/proc/28/task/28/exe"
file has vanished: "/proc/29/exe"
file has vanished: "/proc/29/task/29/exe"
rsync: failed to set times on "/proc/28": Operation not permitted (1)
rsync: failed to set times on "/proc/29": Operation not permitted (1)
file has vanished: "/proc/3/exe"
file has vanished: "/proc/3/task/3/exe"
file has vanished: "/proc/30/exe"
file has vanished: "/proc/30/task/30/exe"
proc/28/
proc/29/
rsync: failed to set times on "/proc/3": Operation not permitted (1)
rsync: failed to set times on "/proc/30": Operation not permitted (1)
rsync: failed to set times on "/proc/3012": Operation not permitted (1)
proc/3/
proc/30/
proc/3012/
file has vanished: "/proc/31/exe"
file has vanished: "/proc/31/task/31/exe"
rsync: failed to set times on "/proc/3033": Operation not permitted (1)
rsync: failed to set times on "/proc/31": Operation not permitted (1)
rsync: failed to set times on "/proc/3152": Operation not permitted (1)
proc/3033/
proc/31/
proc/3152/
rsync: failed to set times on "/proc/3272": Operation not permitted (1)
rsync: failed to set times on "/proc/3278": Operation not permitted (1)
proc/3272/
proc/3278/
rsync: failed to set times on "/proc/3279": Operation not permitted (1)
rsync: failed to set times on "/proc/3360": Operation not permitted (1)
rsync: failed to set times on "/proc/3373": Operation not permitted (1)
proc/3279/
proc/3360/
proc/3373/
rsync: failed to set times on "/proc/3374": Operation not permitted (1)
rsync: failed to set times on "/proc/3990": Operation not permitted (1)
rsync: failed to set times on "/proc/3991": Operation not permitted (1)
file has vanished: "/proc/4/exe"
proc/3374/
file has vanished: "/proc/4/task/4/exe"
file has vanished: "/proc/410/exe"
file has vanished: "/proc/410/task/410/exe"
proc/3990/
file has vanished: "/proc/411/exe"
file has vanished: "/proc/411/task/411/exe"
proc/3991/
rsync: failed to set times on "/proc/4": Operation not permitted (1)
rsync: failed to set times on "/proc/410": Operation not permitted (1)
rsync: failed to set times on "/proc/411": Operation not permitted (1)
rsync: failed to set times on "/proc/4181": Operation not permitted (1)
proc/4/
proc/410/
proc/411/
proc/4181/
rsync: failed to set times on "/proc/4289": Operation not permitted (1)
rsync: symlink "/proc/4289/fd/3" -> "/proc/4289/fd" failed: No such file or directory (2)
rsync: symlink "/proc/4289/task/4289/fd/3" -> "/proc/4289/task/4289/fd" failed: No such file or directory (2)
rsync: failed to set times on "/proc/4290": Operation not permitted (1)
directory has vanished: "/proc/4303"
file has vanished: "/proc/449/exe"
file has vanished: "/proc/449/task/449/exe"
proc/4289/
file has vanished: "/proc/4289/fdinfo/3"
file has vanished: "/proc/47/exe"
file has vanished: "/proc/4289/task/4289/fdinfo/3"
file has vanished: "/proc/47/task/47/exe"
proc/4290/
rsync: failed to set times on "/proc/4291": Operation not permitted (1)
file has vanished: "/proc/48/exe"
file has vanished: "/proc/48/task/48/exe"
file has vanished: "/proc/49/exe"
proc/4291/
file has vanished: "/proc/49/task/49/exe"
rsync: recv_generator: mkdir "/proc/4303" failed: No such file or directory (2)
*** Skipping any contents from this failed directory ***
rsync: failed to set times on "/proc/449": Operation not permitted (1)
rsync: failed to set times on "/proc/47": Operation not permitted (1)
rsync: failed to set times on "/proc/48": Operation not permitted (1)
rsync: failed to set times on "/proc/49": Operation not permitted (1)
file has vanished: "/proc/5/exe"
proc/4303/
proc/449/
file has vanished: "/proc/5/task/5/exe"
file has vanished: "/proc/50/exe"
proc/47/
file has vanished: "/proc/50/task/50/exe"
file has vanished: "/proc/51/exe"
proc/48/
file has vanished: "/proc/51/task/51/exe"
file has vanished: "/proc/52/exe"
proc/49/
file has vanished: "/proc/52/task/52/exe"
rsync: failed to set times on "/proc/5": Operation not permitted (1)
rsync: failed to set times on "/proc/50": Operation not permitted (1)
rsync: failed to set times on "/proc/51": Operation not permitted (1)
rsync: failed to set times on "/proc/52": Operation not permitted (1)
file has vanished: "/proc/53/exe"
proc/5/
file has vanished: "/proc/53/task/53/exe"
file has vanished: "/proc/54/exe"
proc/50/
file has vanished: "/proc/54/task/54/exe"
file has vanished: "/proc/55/exe"
proc/51/
file has vanished: "/proc/55/task/55/exe"
file has vanished: "/proc/56/exe"
proc/52/
file has vanished: "/proc/56/task/56/exe"
file has vanished: "/proc/57/exe"
rsync: failed to set times on "/proc/53": Operation not permitted (1)
rsync: failed to set times on "/proc/54": Operation not permitted (1)
rsync: failed to set times on "/proc/55": Operation not permitted (1)
rsync: failed to set times on "/proc/56": Operation not permitted (1)
proc/53/
file has vanished: "/proc/57/task/57/exe"
file has vanished: "/proc/58/exe"
proc/54/
file has vanished: "/proc/58/task/58/exe"
file has vanished: "/proc/59/exe"
proc/55/
file has vanished: "/proc/59/task/59/exe"
file has vanished: "/proc/6/exe"
proc/56/
file has vanished: "/proc/6/task/6/exe"
rsync: failed to set times on "/proc/57": Operation not permitted (1)
file has vanished: "/proc/60/exe"
proc/57/
rsync: failed to set times on "/proc/58": Operation not permitted (1)
rsync: failed to set times on "/proc/59": Operation not permitted (1)
rsync: failed to set times on "/proc/6": Operation not permitted (1)
file has vanished: "/proc/60/task/60/exe"
file has vanished: "/proc/61/exe"
proc/58/
file has vanished: "/proc/61/task/61/exe"
file has vanished: "/proc/62/exe"
proc/59/
file has vanished: "/proc/62/task/62/exe"
proc/6/
rsync: failed to set times on "/proc/60": Operation not permitted (1)
proc/60/
rsync: failed to set times on "/proc/61": Operation not permitted (1)
rsync: failed to set times on "/proc/62": Operation not permitted (1)
rsync: failed to set times on "/proc/663": Operation not permitted (1)
proc/61/
file has vanished: "/proc/68/exe"
proc/62/
file has vanished: "/proc/68/task/68/exe"
file has vanished: "/proc/7/exe"
proc/663/
file has vanished: "/proc/7/task/7/exe"
file has vanished: "/proc/8/exe"
rsync: failed to set times on "/proc/668": Operation not permitted (1)
file has vanished: "/proc/8/task/8/exe"
proc/668/
rsync: failed to set times on "/proc/68": Operation not permitted (1)
rsync: failed to set times on "/proc/7": Operation not permitted (1)
rsync: failed to set times on "/proc/8": Operation not permitted (1)
file has vanished: "/proc/81/exe"
file has vanished: "/proc/81/task/81/exe"
file has vanished: "/proc/82/exe"
proc/68/
file has vanished: "/proc/82/task/82/exe"
file has vanished: "/proc/820/exe"
proc/7/
file has vanished: "/proc/820/task/820/exe"
file has vanished: "/proc/854/exe"
proc/8/
file has vanished: "/proc/854/task/854/exe"
file has vanished: "/proc/859/exe"
rsync: failed to set times on "/proc/81": Operation not permitted (1)
rsync: failed to set times on "/proc/82": Operation not permitted (1)
rsync: failed to set times on "/proc/820": Operation not permitted (1)
rsync: failed to set times on "/proc/854": Operation not permitted (1)
proc/81/
file has vanished: "/proc/859/task/859/exe"
file has vanished: "/proc/9/exe"
proc/82/
file has vanished: "/proc/9/task/9/exe"
proc/820/
proc/854/
rsync: failed to set times on "/proc/859": Operation not permitted (1)
proc/859/
rsync: failed to set times on "/proc/9": Operation not permitted (1)
proc/9/
proc/acpi/
proc/bus/
proc/driver/
proc/fs/
proc/irq/
proc/scsi/
proc/sys/
proc/sysvipc/
proc/tty/
sys/kernel/debug/tracing/

sent 42,142,586 bytes  received 241,032 bytes  405,584.86 bytes/sec
total size is 140,766,266,114,202  speedup is 3,321,242.33
rsync warning: some files vanished before they could be transferred (code 24) at main.c(1183) [sender=3.1.0]
chown: cannot access ‘’: No such file or directory
mydomain.com created in ee v4
-----> Switching EasyEngine v4 sites to port 80
-----> Disabling EasyEngine v3.
HHVM is not installed
Stop : nginx     [OK]
Stop : php5-fpm  [OK]
Stop : mysql     [OK]
Stop : postfix   [OK]
PHP Parse error:  syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in phar:///usr/local/bin/ee4/vendor/easyengine/auth-command/src/Auth_Command.php on line 657
PHP Parse error:  syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in phar:///usr/local/bin/ee4/vendor/easyengine/auth-command/src/Auth_Command.php on line 657
sed: can't read docker-compose.yml: No such file or directory
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

Error: No such container: ee-global-redis
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

-----> Replacing `ee` executable with EasyEngine v4.
-----> Now running `ee` will execute EasyEngine v4.
-----> Migration is complete.
root@MYSERVER:/#
```
